<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


/**
 * ActivityLog200ApplicationJSON - Activity log response
 * 
 * @package calendly\calendly\Models\Operations
 * @access public
 */
class ActivityLog200ApplicationJSON
{
    /**
     * The set of activity log entries matching the criteria
     * 
     * @var array<\calendly\calendly\Models\Shared\Entry> $collection
     */
	#[\JMS\Serializer\Annotation\SerializedName('collection')]
    #[\JMS\Serializer\Annotation\Type('array<calendly\calendly\Models\Shared\Entry>')]
    public array $collection;
    
    /**
     * If there are more search results than the total_count field indicates, pagination will continue to return results past the total_count field value.
     * 
     * @var bool $exceedsMaxTotalCount
     */
	#[\JMS\Serializer\Annotation\SerializedName('exceeds_max_total_count')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $exceedsMaxTotalCount;
    
    /**
     * The date and time of the newest entry (format: "2020-01-02T03:04:05.678Z") in the collection array.
     * 
     * @var ?\DateTime $lastEventTime
     */
	#[\JMS\Serializer\Annotation\SerializedName('last_event_time')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $lastEventTime = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('pagination')]
    #[\JMS\Serializer\Annotation\Type('calendly\calendly\Models\Shared\Pagination')]
    public \calendly\calendly\Models\Shared\Pagination $pagination;
    
    /**
     * Total number of records based on search criteria
     * 
     * @var int $totalCount
     */
	#[\JMS\Serializer\Annotation\SerializedName('total_count')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $totalCount;
    
	public function __construct()
	{
		$this->collection = [];
		$this->exceedsMaxTotalCount = false;
		$this->lastEventTime = null;
		$this->pagination = new \calendly\calendly\Models\Shared\Pagination();
		$this->totalCount = 0;
	}
}
