<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


class DeleteUsersUserUuidWebhooksWebhookUuidRequest
{
	
    public DeleteUsersUserUuidWebhooksWebhookUuidPathParams $pathParams;
    
	public function __construct()
	{
		$this->pathParams = new \calendly\calendly\Models\Operations\DeleteUsersUserUuidWebhooksWebhookUuidPathParams();
	}
}
