<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;

use \calendly\calendly\Utils\SpeakeasyMetadata;
class GetEventTypeAvailableTimesRequest
{
    /**
     * End time of the requested availability range.
     * 
     * @var ?string $endTime
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=end_time')]
    public ?string $endTime = null;
    
    /**
     * The uri associated with the event type
     * 
     * @var ?string $eventType
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=event_type')]
    public ?string $eventType = null;
    
    /**
     * Start time of the requested availability range.
     * 
     * @var ?string $startTime
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=start_time')]
    public ?string $startTime = null;
    
	public function __construct()
	{
		$this->endTime = null;
		$this->eventType = null;
		$this->startTime = null;
	}
}
