<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


/**
 * GetEventTypesUuid200ApplicationJSON - OK
 * 
 * @package calendly\calendly\Models\Operations
 * @access public
 */
class GetEventTypesUuid200ApplicationJSON
{
    /**
     * A configuration for an Event
     * 
     * @var \calendly\calendly\Models\Shared\EventType $resource
     */
	#[\JMS\Serializer\Annotation\SerializedName('resource')]
    #[\JMS\Serializer\Annotation\Type('calendly\calendly\Models\Shared\EventType')]
    public \calendly\calendly\Models\Shared\EventType $resource;
    
	public function __construct()
	{
		$this->resource = new \calendly\calendly\Models\Shared\EventType();
	}
}
