<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


class GetEventTypesResponse
{
	
    public string $contentType;
    
    /**
     * Request is not valid
     * 
     * @var ?\calendly\calendly\Models\Operations\GetEventTypesErrorResponse $errorResponse
     */
	
    public ?GetEventTypesErrorResponse $errorResponse = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\calendly\calendly\Models\Operations\GetEventTypes200ApplicationJSON $getEventTypes200ApplicationJSONObject
     */
	
    public ?GetEventTypes200ApplicationJSON $getEventTypes200ApplicationJSONObject = null;
    
    /**
     * Permission Denied
     * 
     * @var ?\calendly\calendly\Models\Operations\GetEventTypes403ApplicationJSON $getEventTypes403ApplicationJSONObject
     */
	
    public ?GetEventTypes403ApplicationJSON $getEventTypes403ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->errorResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getEventTypes200ApplicationJSONObject = null;
		$this->getEventTypes403ApplicationJSONObject = null;
	}
}
