<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


class GetInviteesResponse
{
	
    public string $contentType;
    
    /**
     * Request is not valid
     * 
     * @var ?\calendly\calendly\Models\Operations\GetInviteesErrorResponse $errorResponse
     */
	
    public ?GetInviteesErrorResponse $errorResponse = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\calendly\calendly\Models\Operations\GetInvitees200ApplicationJSON $getInvitees200ApplicationJSONObject
     */
	
    public ?GetInvitees200ApplicationJSON $getInvitees200ApplicationJSONObject = null;
    
    /**
     * Permission Denied
     * 
     * @var ?\calendly\calendly\Models\Operations\GetInvitees403ApplicationJSON $getInvitees403ApplicationJSONObject
     */
	
    public ?GetInvitees403ApplicationJSON $getInvitees403ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->errorResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getInvitees200ApplicationJSONObject = null;
		$this->getInvitees403ApplicationJSONObject = null;
	}
}
