<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


class GetOrganizationsUuidMembershipsResponse
{
	
    public string $contentType;
    
    /**
     * Request is not valid
     * 
     * @var ?\calendly\calendly\Models\Operations\GetOrganizationsUuidMembershipsErrorResponse $errorResponse
     */
	
    public ?GetOrganizationsUuidMembershipsErrorResponse $errorResponse = null;
    
    /**
     * Caller not authorized to perform this action
     * 
     * @var ?\calendly\calendly\Models\Shared\ErrorResponse $errorResponse1
     */
	
    public ?\calendly\calendly\Models\Shared\ErrorResponse $errorResponse1 = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\calendly\calendly\Models\Operations\GetOrganizationsUuidMemberships200ApplicationJSON $getOrganizationsUuidMemberships200ApplicationJSONObject
     */
	
    public ?GetOrganizationsUuidMemberships200ApplicationJSON $getOrganizationsUuidMemberships200ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->errorResponse = null;
		$this->errorResponse1 = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getOrganizationsUuidMemberships200ApplicationJSONObject = null;
	}
}
