<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


/**
 * GetRoutingFormsUuid200ApplicationJSON - OK
 * 
 * @package calendly\calendly\Models\Operations
 * @access public
 */
class GetRoutingFormsUuid200ApplicationJSON
{
    /**
     * Information about a routing form.
     * 
     * @var \calendly\calendly\Models\Shared\RoutingForm $resource
     */
	#[\JMS\Serializer\Annotation\SerializedName('resource')]
    #[\JMS\Serializer\Annotation\Type('calendly\calendly\Models\Shared\RoutingForm')]
    public \calendly\calendly\Models\Shared\RoutingForm $resource;
    
	public function __construct()
	{
		$this->resource = new \calendly\calendly\Models\Shared\RoutingForm();
	}
}
