<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


/**
 * GetScheduledEventsUuid200ApplicationJSON - OK
 * 
 * @package calendly\calendly\Models\Operations
 * @access public
 */
class GetScheduledEventsUuid200ApplicationJSON
{
    /**
     * Information about a scheduled meeting
     * 
     * @var \calendly\calendly\Models\Shared\Event $resource
     */
	#[\JMS\Serializer\Annotation\SerializedName('resource')]
    #[\JMS\Serializer\Annotation\Type('calendly\calendly\Models\Shared\Event')]
    public \calendly\calendly\Models\Shared\Event $resource;
    
	public function __construct()
	{
		$this->resource = new \calendly\calendly\Models\Shared\Event();
	}
}
