<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


class GetScheduledEventsUuidResponse
{
	
    public string $contentType;
    
    /**
     * Cannot authenticate caller
     * 
     * @var ?\calendly\calendly\Models\Operations\GetScheduledEventsUuidErrorResponse $errorResponse
     */
	
    public ?GetScheduledEventsUuidErrorResponse $errorResponse = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\calendly\calendly\Models\Operations\GetScheduledEventsUuid200ApplicationJSON $getScheduledEventsUuid200ApplicationJSONObject
     */
	
    public ?GetScheduledEventsUuid200ApplicationJSON $getScheduledEventsUuid200ApplicationJSONObject = null;
    
    /**
     * Permission Denied
     * 
     * @var ?\calendly\calendly\Models\Operations\GetScheduledEventsUuid403ApplicationJSON $getScheduledEventsUuid403ApplicationJSONObject
     */
	
    public ?GetScheduledEventsUuid403ApplicationJSON $getScheduledEventsUuid403ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->errorResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getScheduledEventsUuid200ApplicationJSONObject = null;
		$this->getScheduledEventsUuid403ApplicationJSONObject = null;
	}
}
