<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


/**
 * GetScheduledEventsEventUuidInviteesInviteeUuid200ApplicationJSON - OK
 * 
 * @package calendly\calendly\Models\Operations
 * @access public
 */
class GetScheduledEventsEventUuidInviteesInviteeUuid200ApplicationJSON
{
    /**
     * An individual who has been invited to meet with a Calendly member
     * 
     * @var \calendly\calendly\Models\Shared\Invitee $resource
     */
	#[\JMS\Serializer\Annotation\SerializedName('resource')]
    #[\JMS\Serializer\Annotation\Type('calendly\calendly\Models\Shared\Invitee')]
    public \calendly\calendly\Models\Shared\Invitee $resource;
    
	public function __construct()
	{
		$this->resource = new \calendly\calendly\Models\Shared\Invitee();
	}
}
