<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


class GetScheduledEventsResponse
{
	
    public string $contentType;
    
    /**
     * Request is not valid
     * 
     * @var ?\calendly\calendly\Models\Operations\GetScheduledEventsErrorResponse $errorResponse
     */
	
    public ?GetScheduledEventsErrorResponse $errorResponse = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\calendly\calendly\Models\Operations\GetScheduledEvents200ApplicationJSON $getScheduledEvents200ApplicationJSONObject
     */
	
    public ?GetScheduledEvents200ApplicationJSON $getScheduledEvents200ApplicationJSONObject = null;
    
    /**
     * Permission Denied
     * 
     * @var ?\calendly\calendly\Models\Operations\GetScheduledEvents403ApplicationJSON $getScheduledEvents403ApplicationJSONObject
     */
	
    public ?GetScheduledEvents403ApplicationJSON $getScheduledEvents403ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->errorResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getScheduledEvents200ApplicationJSONObject = null;
		$this->getScheduledEvents403ApplicationJSONObject = null;
	}
}
