<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


/**
 * GetUsersUserUuidWebhooksWebhookUuid200ApplicationJSON - OK
 * 
 * @package calendly\calendly\Models\Operations
 * @access public
 */
class GetUsersUserUuidWebhooksWebhookUuid200ApplicationJSON
{
    /**
     * Webhook Subscription Object
     * 
     * @var \calendly\calendly\Models\Shared\WebhookSubscription $resource
     */
	#[\JMS\Serializer\Annotation\SerializedName('resource')]
    #[\JMS\Serializer\Annotation\Type('calendly\calendly\Models\Shared\WebhookSubscription')]
    public \calendly\calendly\Models\Shared\WebhookSubscription $resource;
    
	public function __construct()
	{
		$this->resource = new \calendly\calendly\Models\Shared\WebhookSubscription();
	}
}
