<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


enum GetUserBusyTimes403ApplicationJSONMessageEnum: string
{
    case THIS_USER_IS_NOT_IN_YOUR_ORGANIZATION = 'This user is not in your organization';
}
