<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


class GetUserBusyTimesResponse
{
	
    public string $contentType;
    
    /**
     * Request is not valid
     * 
     * @var ?\calendly\calendly\Models\Operations\GetUserBusyTimesErrorResponse $errorResponse
     */
	
    public ?GetUserBusyTimesErrorResponse $errorResponse = null;
    
    /**
     * Unable to access external calendar
     * 
     * @var ?\calendly\calendly\Models\Shared\ErrorResponse $errorResponse1
     */
	
    public ?\calendly\calendly\Models\Shared\ErrorResponse $errorResponse1 = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\calendly\calendly\Models\Operations\GetUserBusyTimes200ApplicationJSON $getUserBusyTimes200ApplicationJSONObject
     */
	
    public ?GetUserBusyTimes200ApplicationJSON $getUserBusyTimes200ApplicationJSONObject = null;
    
    /**
     * Permission Denied
     * 
     * @var ?\calendly\calendly\Models\Operations\GetUserBusyTimes403ApplicationJSON $getUserBusyTimes403ApplicationJSONObject
     */
	
    public ?GetUserBusyTimes403ApplicationJSON $getUserBusyTimes403ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->errorResponse = null;
		$this->errorResponse1 = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getUserBusyTimes200ApplicationJSONObject = null;
		$this->getUserBusyTimes403ApplicationJSONObject = null;
	}
}
