<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


class GetUserAvailabilitySchedulesUuidResponse
{
	
    public string $contentType;
    
    /**
     * Request is not valid
     * 
     * @var ?\calendly\calendly\Models\Operations\GetUserAvailabilitySchedulesUuidErrorResponse $errorResponse
     */
	
    public ?GetUserAvailabilitySchedulesUuidErrorResponse $errorResponse = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\calendly\calendly\Models\Operations\GetUserAvailabilitySchedulesUuid200ApplicationJSON $getUserAvailabilitySchedulesUuid200ApplicationJSONObject
     */
	
    public ?GetUserAvailabilitySchedulesUuid200ApplicationJSON $getUserAvailabilitySchedulesUuid200ApplicationJSONObject = null;
    
    /**
     * Permission Denied
     * 
     * @var ?\calendly\calendly\Models\Operations\GetUserAvailabilitySchedulesUuid403ApplicationJSON $getUserAvailabilitySchedulesUuid403ApplicationJSONObject
     */
	
    public ?GetUserAvailabilitySchedulesUuid403ApplicationJSON $getUserAvailabilitySchedulesUuid403ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->errorResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getUserAvailabilitySchedulesUuid200ApplicationJSONObject = null;
		$this->getUserAvailabilitySchedulesUuid403ApplicationJSONObject = null;
	}
}
