<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


/**
 * GetUserAvailabilitySchedules200ApplicationJSON - OK
 * 
 * @package calendly\calendly\Models\Operations
 * @access public
 */
class GetUserAvailabilitySchedules200ApplicationJSON
{
    /**
     * $collection
     * 
     * @var array<\calendly\calendly\Models\Shared\AvailabilitySchedule> $collection
     */
	#[\JMS\Serializer\Annotation\SerializedName('collection')]
    #[\JMS\Serializer\Annotation\Type('array<calendly\calendly\Models\Shared\AvailabilitySchedule>')]
    public array $collection;
    
	public function __construct()
	{
		$this->collection = [];
	}
}
