<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;

use \calendly\calendly\Utils\SpeakeasyMetadata;
class GetUserBusyTimesRequest
{
    /**
     * End time of the requested availability range
     * 
     * @var string $endTime
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=end_time')]
    public string $endTime;
    
    /**
     * Start time of the requested availability range
     * 
     * @var string $startTime
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=start_time')]
    public string $startTime;
    
    /**
     * The uri associated with the user
     * 
     * @var string $user
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=user')]
    public string $user;
    
	public function __construct()
	{
		$this->endTime = "";
		$this->startTime = "";
		$this->user = "";
	}
}
