<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


enum GetUserBusyTimes403ApplicationJSONTitleEnum: string
{
    case PERMISSION_DENIED = 'Permission Denied';
}
