<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


/**
 * GetUserAvailabilitySchedulesUuid200ApplicationJSON - OK
 * 
 * @package calendly\calendly\Models\Operations
 * @access public
 */
class GetUserAvailabilitySchedulesUuid200ApplicationJSON
{
    /**
     * The availability schedule set by the user.
     * 
     * @var \calendly\calendly\Models\Shared\AvailabilitySchedule $resource
     */
	#[\JMS\Serializer\Annotation\SerializedName('resource')]
    #[\JMS\Serializer\Annotation\Type('calendly\calendly\Models\Shared\AvailabilitySchedule')]
    public \calendly\calendly\Models\Shared\AvailabilitySchedule $resource;
    
	public function __construct()
	{
		$this->resource = new \calendly\calendly\Models\Shared\AvailabilitySchedule();
	}
}
