<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


/** Filter the list by organization or user */
enum GetWebhooksScopeEnum: string
{
    case ORGANIZATION = 'organization';
    case USER = 'user';
}
