<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


class GetWebhooksResponse
{
	
    public string $contentType;
    
    /**
     * Request is not valid
     * 
     * @var ?\calendly\calendly\Models\Operations\GetWebhooksErrorResponse $errorResponse
     */
	
    public ?GetWebhooksErrorResponse $errorResponse = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\calendly\calendly\Models\Operations\GetWebhooks200ApplicationJSON $getWebhooks200ApplicationJSONObject
     */
	
    public ?GetWebhooks200ApplicationJSON $getWebhooks200ApplicationJSONObject = null;
    
    /**
     * Permission Denied
     * 
     * @var ?\calendly\calendly\Models\Operations\GetWebhooks403ApplicationJSON $getWebhooks403ApplicationJSONObject
     */
	
    public ?GetWebhooks403ApplicationJSON $getWebhooks403ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->errorResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getWebhooks200ApplicationJSONObject = null;
		$this->getWebhooks403ApplicationJSONObject = null;
	}
}
