<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;

use \calendly\calendly\Utils\SpeakeasyMetadata;
class ListScheduledEventsRequest
{
    /**
     * The number of rows to return
     * 
     * @var ?float $count
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=count')]
    public ?float $count = null;
    
    /**
     * Return events that are scheduled with the invitee associated with this email address
     * 
     * @var ?string $inviteeEmail
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=invitee_email')]
    public ?string $inviteeEmail = null;
    
    /**
     * Include events with start times prior to this time (sample time format: "2020-01-02T03:04:05.678123Z"). This time should use the UTC timezone.
     * 
     * @var ?string $maxStartTime
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=max_start_time')]
    public ?string $maxStartTime = null;
    
    /**
     * Include events with start times after this time (sample time format: "2020-01-02T03:04:05.678123Z"). This time should use the UTC timezone.
     * 
     * @var ?string $minStartTime
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=min_start_time')]
    public ?string $minStartTime = null;
    
    /**
     * Return events that are scheduled with the organization associated with this URI
     * 
     * @var ?string $organization
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=organization')]
    public ?string $organization = null;
    
    /**
     * The token to pass to get the next or previous portion of the collection
     * 
     * @var ?string $pageToken
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=page_token')]
    public ?string $pageToken = null;
    
    /**
     * Order results by the specified field and direction. Accepts comma-separated list of {field}:{direction} values.
     * 
     * Supported fields are: start_time.
     * Sort direction is specified as: asc, desc.
     * 
     * @var ?string $sort
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=sort')]
    public ?string $sort = null;
    
    /**
     * Whether the scheduled event is `active` or `canceled`
     * 
     * @var ?\calendly\calendly\Models\Operations\ListScheduledEventsStatusEnum $status
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=status')]
    public ?ListScheduledEventsStatusEnum $status = null;
    
    /**
     * Return events that are scheduled with the user associated with this URI
     * 
     * @var ?string $user
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=user')]
    public ?string $user = null;
    
	public function __construct()
	{
		$this->count = null;
		$this->inviteeEmail = null;
		$this->maxStartTime = null;
		$this->minStartTime = null;
		$this->organization = null;
		$this->pageToken = null;
		$this->sort = null;
		$this->status = null;
		$this->user = null;
	}
}
