<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


class ListActivityLogResponse
{
	
    public string $contentType;
    
    /**
     * Request is not valid
     * 
     * @var ?\calendly\calendly\Models\Operations\ListActivityLogErrorResponse $errorResponse
     */
	
    public ?ListActivityLogErrorResponse $errorResponse = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\calendly\calendly\Models\Operations\ListActivityLog200ApplicationJSON $listActivityLog200ApplicationJSONObject
     */
	
    public ?ListActivityLog200ApplicationJSON $listActivityLog200ApplicationJSONObject = null;
    
    /**
     * Permission Denied
     * 
     * @var ?\calendly\calendly\Models\Operations\ListActivityLog403ApplicationJSON $listActivityLog403ApplicationJSONObject
     */
	
    public ?ListActivityLog403ApplicationJSON $listActivityLog403ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->errorResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->listActivityLog200ApplicationJSONObject = null;
		$this->listActivityLog403ApplicationJSONObject = null;
	}
}
