<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


class ListScheduledEventsResponse
{
	
    public string $contentType;
    
    /**
     * Request is not valid
     * 
     * @var ?\calendly\calendly\Models\Operations\ListScheduledEventsErrorResponse $errorResponse
     */
	
    public ?ListScheduledEventsErrorResponse $errorResponse = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\calendly\calendly\Models\Operations\ListScheduledEvents200ApplicationJSON $listScheduledEvents200ApplicationJSONObject
     */
	
    public ?ListScheduledEvents200ApplicationJSON $listScheduledEvents200ApplicationJSONObject = null;
    
    /**
     * Permission Denied
     * 
     * @var ?\calendly\calendly\Models\Operations\ListScheduledEvents403ApplicationJSON $listScheduledEvents403ApplicationJSONObject
     */
	
    public ?ListScheduledEvents403ApplicationJSON $listScheduledEvents403ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->errorResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->listScheduledEvents200ApplicationJSONObject = null;
		$this->listScheduledEvents403ApplicationJSONObject = null;
	}
}
