<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


/** Whether the scheduled event is `active` or `canceled` */
enum ListScheduledEventsStatusEnum: string
{
    case ACTIVE = 'active';
    case CANCELED = 'canceled';
}
