<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


class ListEventTypesResponse
{
	
    public string $contentType;
    
    /**
     * Request is not valid
     * 
     * @var ?\calendly\calendly\Models\Operations\ListEventTypesErrorResponse $errorResponse
     */
	
    public ?ListEventTypesErrorResponse $errorResponse = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\calendly\calendly\Models\Operations\ListEventTypes200ApplicationJSON $listEventTypes200ApplicationJSONObject
     */
	
    public ?ListEventTypes200ApplicationJSON $listEventTypes200ApplicationJSONObject = null;
    
    /**
     * Permission Denied
     * 
     * @var ?\calendly\calendly\Models\Operations\ListEventTypes403ApplicationJSON $listEventTypes403ApplicationJSONObject
     */
	
    public ?ListEventTypes403ApplicationJSON $listEventTypes403ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->errorResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->listEventTypes200ApplicationJSONObject = null;
		$this->listEventTypes403ApplicationJSONObject = null;
	}
}
