<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


class ListWebhooksResponse
{
	
    public string $contentType;
    
    /**
     * Request is not valid
     * 
     * @var ?\calendly\calendly\Models\Operations\ListWebhooksErrorResponse $errorResponse
     */
	
    public ?ListWebhooksErrorResponse $errorResponse = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\calendly\calendly\Models\Operations\ListWebhooks200ApplicationJSON $listWebhooks200ApplicationJSONObject
     */
	
    public ?ListWebhooks200ApplicationJSON $listWebhooks200ApplicationJSONObject = null;
    
    /**
     * Permission Denied
     * 
     * @var ?\calendly\calendly\Models\Operations\ListWebhooks403ApplicationJSON $listWebhooks403ApplicationJSONObject
     */
	
    public ?ListWebhooks403ApplicationJSON $listWebhooks403ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->errorResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->listWebhooks200ApplicationJSONObject = null;
		$this->listWebhooks403ApplicationJSONObject = null;
	}
}
