<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;

use \calendly\calendly\Utils\SpeakeasyMetadata;
class PostScheduledEventsUuidCancellationRawRequest
{
	
    public PostScheduledEventsUuidCancellationPathParams $pathParams;
    
    /**
     * Optional cancellation reason.
     * 
     * @var ?string $request
     */
	#[SpeakeasyMetadata('request:mediaType=application/xml')]
    public ?string $request = null;
    
	public function __construct()
	{
		$this->pathParams = new \calendly\calendly\Models\Operations\PostScheduledEventsUuidCancellationPathParams();
		$this->request = null;
	}
}
