<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


/** The max number of events that can be scheduled using this scheduling link. */
enum PostSchedulingLinksRequestBodyMaxEventCountEnum: string
{
    case ONE = '1';
}
