<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


class PostDataComplianceDeletionInviteesRequestBody
{
    /**
     * $emails
     * 
     * @var array<string> $emails
     */
	#[\JMS\Serializer\Annotation\SerializedName('emails')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    public array $emails;
    
	public function __construct()
	{
		$this->emails = [];
	}
}
