<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


/**
 * PostSchedulingLinks201ApplicationJSON - Created
 * 
 * @package calendly\calendly\Models\Operations
 * @access public
 */
class PostSchedulingLinks201ApplicationJSON
{
	#[\JMS\Serializer\Annotation\SerializedName('resource')]
    #[\JMS\Serializer\Annotation\Type('calendly\calendly\Models\Operations\PostSchedulingLinks201ApplicationJSONResource')]
    public PostSchedulingLinks201ApplicationJSONResource $resource;
    
	public function __construct()
	{
		$this->resource = new \calendly\calendly\Models\Operations\PostSchedulingLinks201ApplicationJSONResource();
	}
}
