<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


class PostScheduledEventsUuidCancellationRawResponse
{
	
    public string $contentType;
    
    /**
     * Request is not valid
     * 
     * @var ?\calendly\calendly\Models\Operations\PostScheduledEventsUuidCancellationRawErrorResponse $errorResponse
     */
	
    public ?PostScheduledEventsUuidCancellationRawErrorResponse $errorResponse = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Created
     * 
     * @var ?\calendly\calendly\Models\Operations\PostScheduledEventsUuidCancellationRaw201ApplicationJSON $postScheduledEventsUuidCancellationRaw201ApplicationJSONObject
     */
	
    public ?PostScheduledEventsUuidCancellationRaw201ApplicationJSON $postScheduledEventsUuidCancellationRaw201ApplicationJSONObject = null;
    
    /**
     * Caller not authorized to perform this action
     * 
     * @var ?\calendly\calendly\Models\Operations\PostScheduledEventsUuidCancellationRaw403ApplicationJSON $postScheduledEventsUuidCancellationRaw403ApplicationJSONObject
     */
	
    public ?PostScheduledEventsUuidCancellationRaw403ApplicationJSON $postScheduledEventsUuidCancellationRaw403ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->errorResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->postScheduledEventsUuidCancellationRaw201ApplicationJSONObject = null;
		$this->postScheduledEventsUuidCancellationRaw403ApplicationJSONObject = null;
	}
}
