<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


class PostSharesRequestBodyAvailabilityRule
{
    /**
     * are required when an availability rule is provided
     * 
     * @var ?array<\calendly\calendly\Models\Operations\PostSharesRequestBodyAvailabilityRuleRules> $rules
     */
	#[\JMS\Serializer\Annotation\SerializedName('rules')]
    #[\JMS\Serializer\Annotation\Type('array<calendly\calendly\Models\Operations\PostSharesRequestBodyAvailabilityRuleRules>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $rules = null;
    
    /**
     * is required when an availability rule is provided
     * 
     * @var ?string $timezone
     */
	#[\JMS\Serializer\Annotation\SerializedName('timezone')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $timezone = null;
    
	public function __construct()
	{
		$this->rules = null;
		$this->timezone = null;
	}
}
