<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;

use \calendly\calendly\Utils\SpeakeasyMetadata;
class PostScheduledEventsUuidCancellationMultipartRequest
{
    /**
     * Optional cancellation reason.
     * 
     * @var ?array<string, mixed> $requestBody
     */
	#[SpeakeasyMetadata('request:mediaType=multipart/form-data')]
    public ?array $requestBody = null;
    
    /**
     * The event's unique indentifier
     * 
     * @var string $uuid
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=uuid')]
    public string $uuid;
    
	public function __construct()
	{
		$this->requestBody = null;
		$this->uuid = "";
	}
}
