<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;

use \calendly\calendly\Utils\SpeakeasyMetadata;
class PostDataComplianceDeletionEventsRequest
{
    /**
     * The start and end times that delineate the time range for scheduled events data deletion.
     * 
     * @var \calendly\calendly\Models\Operations\PostDataComplianceDeletionEventsRequestBody $request
     */
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public PostDataComplianceDeletionEventsRequestBody $request;
    
	public function __construct()
	{
		$this->request = new \calendly\calendly\Models\Operations\PostDataComplianceDeletionEventsRequestBody();
	}
}
