<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


class PostUsersUuidWebhooksRequestBody
{
    /**
     * List of user events to subscribe to.
     * 
     * @var array<\calendly\calendly\Models\Operations\PostUsersUuidWebhooksRequestBodyEventsEnum> $events
     */
	#[\JMS\Serializer\Annotation\SerializedName('events')]
    #[\JMS\Serializer\Annotation\Type('array<enum<calendly\calendly\Models\Operations\PostUsersUuidWebhooksRequestBodyEventsEnum>>')]
    public array $events;
    
    /**
     * The unique reference to the organization that the webhook will be tied to.
     * 
     * @var string $organization
     */
	#[\JMS\Serializer\Annotation\SerializedName('organization')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $organization;
    
    /**
     * Indicates if the webhook subscription scope will be "organization" or "user"
     * 
     * @var \calendly\calendly\Models\Operations\PostUsersUuidWebhooksRequestBodyScopeEnum $scope
     */
	#[\JMS\Serializer\Annotation\SerializedName('scope')]
    #[\JMS\Serializer\Annotation\Type('enum<calendly\calendly\Models\Operations\PostUsersUuidWebhooksRequestBodyScopeEnum>')]
    public PostUsersUuidWebhooksRequestBodyScopeEnum $scope;
    
    /**
     * Optional secret key shared between your application and Calendly. See https://developer.calendly.com/api-docs/ZG9jOjM2MzE2MDM4-webhook-signatures for additional information.
     * 
     * @var ?string $signingKey
     */
	#[\JMS\Serializer\Annotation\SerializedName('signing_key')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $signingKey = null;
    
    /**
     * The URL where you want to receive POST requests for events you are subscribed to.
     * 
     * @var string $url
     */
	#[\JMS\Serializer\Annotation\SerializedName('url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $url;
    
    /**
     * The unique reference to the user that the webhook will be tied to.
     * 
     * @var ?string $user
     */
	#[\JMS\Serializer\Annotation\SerializedName('user')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $user = null;
    
	public function __construct()
	{
		$this->events = [];
		$this->organization = "";
		$this->scope = \calendly\calendly\Models\Operations\PostUsersUuidWebhooksRequestBodyScopeEnum::ORGANIZATION;
		$this->signingKey = null;
		$this->url = "";
		$this->user = null;
	}
}
