<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


/**
 * PostScheduledEventsUuidCancellationJSON201ApplicationJSON - Created
 * 
 * @package calendly\calendly\Models\Operations
 * @access public
 */
class PostScheduledEventsUuidCancellationJSON201ApplicationJSON
{
    /**
     * Provides data pertaining to the cancellation of the Event
     * 
     * @var \calendly\calendly\Models\Shared\Cancellation $resource
     */
	#[\JMS\Serializer\Annotation\SerializedName('resource')]
    #[\JMS\Serializer\Annotation\Type('calendly\calendly\Models\Shared\Cancellation')]
    public \calendly\calendly\Models\Shared\Cancellation $resource;
    
	public function __construct()
	{
		$this->resource = new \calendly\calendly\Models\Shared\Cancellation();
	}
}
