<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


class PostDataComplianceDeletionEventsResponse
{
	
    public string $contentType;
    
    /**
     * Request is not valid
     * 
     * @var ?\calendly\calendly\Models\Operations\PostDataComplianceDeletionEventsErrorResponse $errorResponse
     */
	
    public ?PostDataComplianceDeletionEventsErrorResponse $errorResponse = null;
    
    /**
     * Forbidden
     * 
     * @var ?\calendly\calendly\Models\Shared\ErrorResponse $errorResponse1
     */
	
    public ?\calendly\calendly\Models\Shared\ErrorResponse $errorResponse1 = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Accepted
     * 
     * @var ?array<string, mixed> $postDataComplianceDeletionEvents202ApplicationJSONObject
     */
	
    public ?array $postDataComplianceDeletionEvents202ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->errorResponse = null;
		$this->errorResponse1 = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->postDataComplianceDeletionEvents202ApplicationJSONObject = null;
	}
}
