<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


class PostInviteeNoShowResponse
{
	
    public string $contentType;
    
    /**
     * Request is not valid
     * 
     * @var ?\calendly\calendly\Models\Operations\PostInviteeNoShowErrorResponse $errorResponse
     */
	
    public ?PostInviteeNoShowErrorResponse $errorResponse = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Created
     * 
     * @var ?\calendly\calendly\Models\Operations\PostInviteeNoShow201ApplicationJSON $postInviteeNoShow201ApplicationJSONObject
     */
	
    public ?PostInviteeNoShow201ApplicationJSON $postInviteeNoShow201ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->errorResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->postInviteeNoShow201ApplicationJSONObject = null;
	}
}
