<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


class PostScheduledEventsUuidCancellationMultipartResponse
{
	
    public string $contentType;
    
    /**
     * Request is not valid
     * 
     * @var ?\calendly\calendly\Models\Operations\PostScheduledEventsUuidCancellationMultipartErrorResponse $errorResponse
     */
	
    public ?PostScheduledEventsUuidCancellationMultipartErrorResponse $errorResponse = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Created
     * 
     * @var ?\calendly\calendly\Models\Operations\PostScheduledEventsUuidCancellationMultipart201ApplicationJSON $postScheduledEventsUuidCancellationMultipart201ApplicationJSONObject
     */
	
    public ?PostScheduledEventsUuidCancellationMultipart201ApplicationJSON $postScheduledEventsUuidCancellationMultipart201ApplicationJSONObject = null;
    
    /**
     * Caller not authorized to perform this action
     * 
     * @var ?\calendly\calendly\Models\Operations\PostScheduledEventsUuidCancellationMultipart403ApplicationJSON $postScheduledEventsUuidCancellationMultipart403ApplicationJSONObject
     */
	
    public ?PostScheduledEventsUuidCancellationMultipart403ApplicationJSON $postScheduledEventsUuidCancellationMultipart403ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->errorResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->postScheduledEventsUuidCancellationMultipart201ApplicationJSONObject = null;
		$this->postScheduledEventsUuidCancellationMultipart403ApplicationJSONObject = null;
	}
}
