<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


class PostOrganizationsUuidInvitationsResponse
{
	
    public string $contentType;
    
    /**
     * Cannot authenticate caller
     * 
     * @var ?\calendly\calendly\Models\Operations\PostOrganizationsUuidInvitationsErrorResponse $errorResponse1
     */
	
    public ?PostOrganizationsUuidInvitationsErrorResponse $errorResponse1 = null;
    
    /**
     * Bad Request
     * 
     * @var ?\calendly\calendly\Models\Shared\ErrorResponse $errorResponse
     */
	
    public ?\calendly\calendly\Models\Shared\ErrorResponse $errorResponse = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Created
     * 
     * @var ?\calendly\calendly\Models\Operations\PostOrganizationsUuidInvitations201ApplicationJSON $postOrganizationsUuidInvitations201ApplicationJSONObject
     */
	
    public ?PostOrganizationsUuidInvitations201ApplicationJSON $postOrganizationsUuidInvitations201ApplicationJSONObject = null;
    
    /**
     * Permission Denied
     * 
     * @var ?\calendly\calendly\Models\Operations\PostOrganizationsUuidInvitations403ApplicationJSON $postOrganizationsUuidInvitations403ApplicationJSONObject
     */
	
    public ?PostOrganizationsUuidInvitations403ApplicationJSON $postOrganizationsUuidInvitations403ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->errorResponse1 = null;
		$this->errorResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->postOrganizationsUuidInvitations201ApplicationJSONObject = null;
		$this->postOrganizationsUuidInvitations403ApplicationJSONObject = null;
	}
}
