<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


class PostDataComplianceDeletionInviteesResponse
{
	
    public string $contentType;
    
    /**
     * Request is not valid
     * 
     * @var ?\calendly\calendly\Models\Operations\PostDataComplianceDeletionInviteesErrorResponse $errorResponse
     */
	
    public ?PostDataComplianceDeletionInviteesErrorResponse $errorResponse = null;
    
    /**
     * Forbidden
     * 
     * @var ?\calendly\calendly\Models\Shared\ErrorResponse $errorResponse1
     */
	
    public ?\calendly\calendly\Models\Shared\ErrorResponse $errorResponse1 = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Accepted
     * 
     * @var ?array<string, mixed> $postDataComplianceDeletionInvitees202ApplicationJSONObject
     */
	
    public ?array $postDataComplianceDeletionInvitees202ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->errorResponse = null;
		$this->errorResponse1 = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->postDataComplianceDeletionInvitees202ApplicationJSONObject = null;
	}
}
