<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


class PostScheduledEventsUuidCancellationJsonResponse
{
	
    public string $contentType;
    
    /**
     * Request is not valid
     * 
     * @var ?\calendly\calendly\Models\Operations\PostScheduledEventsUuidCancellationJsonErrorResponse $errorResponse
     */
	
    public ?PostScheduledEventsUuidCancellationJsonErrorResponse $errorResponse = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Created
     * 
     * @var ?\calendly\calendly\Models\Operations\PostScheduledEventsUuidCancellationJSON201ApplicationJSON $postScheduledEventsUuidCancellationJSON201ApplicationJSONObject
     */
	
    public ?PostScheduledEventsUuidCancellationJSON201ApplicationJSON $postScheduledEventsUuidCancellationJSON201ApplicationJSONObject = null;
    
    /**
     * Caller not authorized to perform this action
     * 
     * @var ?\calendly\calendly\Models\Operations\PostScheduledEventsUuidCancellationJSON403ApplicationJSON $postScheduledEventsUuidCancellationJSON403ApplicationJSONObject
     */
	
    public ?PostScheduledEventsUuidCancellationJSON403ApplicationJSON $postScheduledEventsUuidCancellationJSON403ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->errorResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->postScheduledEventsUuidCancellationJSON201ApplicationJSONObject = null;
		$this->postScheduledEventsUuidCancellationJSON403ApplicationJSONObject = null;
	}
}
