<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


/** Resource type (currently, this is always EventType) */
enum PostSchedulingLinks201ApplicationJSONResourceOwnerTypeEnum: string
{
    case EVENT_TYPE = 'EventType';
}
