<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


class PostUsersUuidWebhooksResponse
{
	
    public string $contentType;
    
    /**
     * Request is not valid
     * 
     * @var ?\calendly\calendly\Models\Operations\PostUsersUuidWebhooksErrorResponse $errorResponse
     */
	
    public ?PostUsersUuidWebhooksErrorResponse $errorResponse = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Created
     * 
     * @var ?\calendly\calendly\Models\Operations\PostUsersUuidWebhooks201ApplicationJSON $postUsersUuidWebhooks201ApplicationJSONObject
     */
	
    public ?PostUsersUuidWebhooks201ApplicationJSON $postUsersUuidWebhooks201ApplicationJSONObject = null;
    
    /**
     * Permission Denied
     * 
     * @var ?\calendly\calendly\Models\Operations\PostUsersUuidWebhooks403ApplicationJSON $postUsersUuidWebhooks403ApplicationJSONObject
     */
	
    public ?PostUsersUuidWebhooks403ApplicationJSON $postUsersUuidWebhooks403ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->errorResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->postUsersUuidWebhooks201ApplicationJSONObject = null;
		$this->postUsersUuidWebhooks403ApplicationJSONObject = null;
	}
}
