<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


class PostSchedulingLinksRequestBody
{
    /**
     * The max number of events that can be scheduled using this scheduling link.
     * 
     * @var \calendly\calendly\Models\Operations\PostSchedulingLinksRequestBodyMaxEventCountEnum $maxEventCount
     */
	#[\JMS\Serializer\Annotation\SerializedName('max_event_count')]
    #[\JMS\Serializer\Annotation\Type('enum<calendly\calendly\Models\Operations\PostSchedulingLinksRequestBodyMaxEventCountEnum>')]
    public PostSchedulingLinksRequestBodyMaxEventCountEnum $maxEventCount;
    
    /**
     * A link to the resource that owns this Scheduling Link (currently, this is always an Event Type)
     * 
     * @var string $owner
     */
	#[\JMS\Serializer\Annotation\SerializedName('owner')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $owner;
    
    /**
     * Resource type (currently, this is always EventType)
     * 
     * @var \calendly\calendly\Models\Operations\PostSchedulingLinksRequestBodyOwnerTypeEnum $ownerType
     */
	#[\JMS\Serializer\Annotation\SerializedName('owner_type')]
    #[\JMS\Serializer\Annotation\Type('enum<calendly\calendly\Models\Operations\PostSchedulingLinksRequestBodyOwnerTypeEnum>')]
    public PostSchedulingLinksRequestBodyOwnerTypeEnum $ownerType;
    
	public function __construct()
	{
		$this->maxEventCount = \calendly\calendly\Models\Operations\PostSchedulingLinksRequestBodyMaxEventCountEnum::ONE;
		$this->owner = "";
		$this->ownerType = \calendly\calendly\Models\Operations\PostSchedulingLinksRequestBodyOwnerTypeEnum::EVENT_TYPE;
	}
}
