<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


class PostSharesRequestBodyAvailabilityRuleRules
{
    /**
     * is required when `type` is 'date'
     * 
     * Format: `YYYY-MM-DD`
     * 
     * @var ?\DateTime $date
     */
	#[\JMS\Serializer\Annotation\SerializedName('date')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d', '', '|Y-m-d'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $date = null;
    
    /**
     * $intervals
     * 
     * @var ?array<\calendly\calendly\Models\Operations\PostSharesRequestBodyAvailabilityRuleRulesIntervals> $intervals
     */
	#[\JMS\Serializer\Annotation\SerializedName('intervals')]
    #[\JMS\Serializer\Annotation\Type('array<calendly\calendly\Models\Operations\PostSharesRequestBodyAvailabilityRuleRulesIntervals>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $intervals = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<calendly\calendly\Models\Operations\PostSharesRequestBodyAvailabilityRuleRulesTypeEnum>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?PostSharesRequestBodyAvailabilityRuleRulesTypeEnum $type = null;
    
    /**
     * is required when `type` is 'wday'
     * 
     * @var ?\calendly\calendly\Models\Operations\PostSharesRequestBodyAvailabilityRuleRulesWdayEnum $wday
     */
	#[\JMS\Serializer\Annotation\SerializedName('wday')]
    #[\JMS\Serializer\Annotation\Type('enum<calendly\calendly\Models\Operations\PostSharesRequestBodyAvailabilityRuleRulesWdayEnum>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?PostSharesRequestBodyAvailabilityRuleRulesWdayEnum $wday = null;
    
	public function __construct()
	{
		$this->date = null;
		$this->intervals = null;
		$this->type = null;
		$this->wday = null;
	}
}
