<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Operations;


class RevokeUsersOrganizationInvitationResponse
{
	
    public string $contentType;
    
    /**
     * Cannot authenticate caller
     * 
     * @var ?\calendly\calendly\Models\Operations\RevokeUsersOrganizationInvitationErrorResponse $errorResponse1
     */
	
    public ?RevokeUsersOrganizationInvitationErrorResponse $errorResponse1 = null;
    
    /**
     * Bad Request
     * 
     * @var ?\calendly\calendly\Models\Shared\ErrorResponse $errorResponse
     */
	
    public ?\calendly\calendly\Models\Shared\ErrorResponse $errorResponse = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Permission Denied
     * 
     * @var ?\calendly\calendly\Models\Operations\RevokeUsersOrganizationInvitation403ApplicationJSON $revokeUsersOrganizationInvitation403ApplicationJSONObject
     */
	
    public ?RevokeUsersOrganizationInvitation403ApplicationJSON $revokeUsersOrganizationInvitation403ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->errorResponse1 = null;
		$this->errorResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->revokeUsersOrganizationInvitation403ApplicationJSONObject = null;
	}
}
