<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/**
 * AvailabilitySchedule - The availability schedule set by the user.
 * 
 * @package calendly\calendly\Models\Shared
 * @access public
 */
class AvailabilitySchedule
{
    /**
     * This is the default Availability Schedule in use.
     * 
     * @var bool $default
     */
	#[\JMS\Serializer\Annotation\SerializedName('default')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $default;
    
    /**
     * The name of this Availability Schedule.
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * The rules of this Availability Schedule.
     * 
     * @var array<\calendly\calendly\Models\Shared\AvailabilityRule> $rules
     */
	#[\JMS\Serializer\Annotation\SerializedName('rules')]
    #[\JMS\Serializer\Annotation\Type('array<calendly\calendly\Models\Shared\AvailabilityRule>')]
    public array $rules;
    
    /**
     * The timezone for which this Availability Schedule is originated in.
     * 
     * @var string $timezone
     */
	#[\JMS\Serializer\Annotation\SerializedName('timezone')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $timezone;
    
    /**
     * A URI reference to this Availability Schedule.
     * 
     * @var string $uri
     */
	#[\JMS\Serializer\Annotation\SerializedName('uri')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $uri;
    
    /**
     * A URI reference to a User.
     * 
     * @var string $user
     */
	#[\JMS\Serializer\Annotation\SerializedName('user')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $user;
    
	public function __construct()
	{
		$this->default = false;
		$this->name = "";
		$this->rules = [];
		$this->timezone = "";
		$this->uri = "";
		$this->user = "";
	}
}
