<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** The type of this Availability Rule; can be "wday" or a specific "date". */
enum AvailabilityRuleTypeEnum: string
{
    case WDAY = 'wday';
    case DATE = 'date';
}
