<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** The event location doesn't fall into a standard category defined by the event host (publisher) */
enum CustomLocationTypeEnum: string
{
    case CUSTOM = 'custom';
}
