<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/**
 * CustomLocation - Use this to describe an existing Calendly-supported event location.
 * 
 * @package calendly\calendly\Models\Shared
 * @access public
 */
class CustomLocation
{
    /**
     * The location description provided by the event host (publisher)
     * 
     * @var string $location
     */
	#[\JMS\Serializer\Annotation\SerializedName('location')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $location;
    
    /**
     * The event location doesn't fall into a standard category defined by the event host (publisher)
     * 
     * @var \calendly\calendly\Models\Shared\CustomLocationTypeEnum $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<calendly\calendly\Models\Shared\CustomLocationTypeEnum>')]
    public CustomLocationTypeEnum $type;
    
	public function __construct()
	{
		$this->location = "";
		$this->type = \calendly\calendly\Models\Shared\CustomLocationTypeEnum::CUSTOM;
	}
}
