<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** Indicates if the event type is "round robin" (alternates between hosts) or "collective" (invitees pick a time when all participants are available) or "null" (the event type doesn’t consider the availability of a group participants) */
enum EventTypePoolingTypeEnum: string
{
    case ROUND_ROBIN = 'round_robin';
    case COLLECTIVE = 'collective';
}
