<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


class EventInviteesCounter
{
    /**
     * Total invitees for an event that have not canceled
     * 
     * @var float $active
     */
	#[\JMS\Serializer\Annotation\SerializedName('active')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $active;
    
    /**
     * Maximum number of active invitees that can book the event
     * 
     * @var float $limit
     */
	#[\JMS\Serializer\Annotation\SerializedName('limit')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $limit;
    
    /**
     * Total invitees for an event, including invitees that have canceled
     * 
     * @var float $total
     */
	#[\JMS\Serializer\Annotation\SerializedName('total')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $total;
    
	public function __construct()
	{
		$this->active = 0;
		$this->limit = 0;
		$this->total = 0;
	}
}
