<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/**
 * EventTypeAvailableTime - An available meeting time slot for the given event type
 * 
 * @package calendly\calendly\Models\Shared
 * @access public
 */
class EventTypeAvailableTime
{
    /**
     * Total remaining invitees for this available time. For Group Event Type, more than one invitee can book in this available time. For all other Event Types, only one invitee can book in this available time.
     * 
     * @var float $inviteesRemaining
     */
	#[\JMS\Serializer\Annotation\SerializedName('invitees_remaining')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $inviteesRemaining;
    
    /**
     * The URL of the user’s scheduling site where invitees book this event type
     * 
     * @var string $schedulingUrl
     */
	#[\JMS\Serializer\Annotation\SerializedName('scheduling_url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $schedulingUrl;
    
    /**
     * The moment the event was scheduled to start in UTC time
     * 
     * @var \DateTime $startTime
     */
	#[\JMS\Serializer\Annotation\SerializedName('start_time')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $startTime;
    
    /**
     * Indicates that the open time slot is "available"
     * 
     * @var string $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $status;
    
	public function __construct()
	{
		$this->inviteesRemaining = 0;
		$this->schedulingUrl = "";
		$this->startTime = new \DateTime();
		$this->status = "";
	}
}
