<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** Indicates if the event type is for a poll or an instant booking */
enum EventTypeBookingMethodEnum: string
{
    case INSTANT = 'instant';
    case POLL = 'poll';
}
