<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** The type of response that the invitee provides to the custom question; can be one or multiple lines of text, a phone number, or single- or multiple-select. */
enum EventTypeCustomQuestionTypeEnum: string
{
    case STRING = 'string';
    case TEXT = 'text';
    case PHONE_NUMBER = 'phone_number';
    case SINGLE_SELECT = 'single_select';
    case MULTI_SELECT = 'multi_select';
}
