<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** Indicates if the event type is "solo" (belongs to an individual user) or "group" */
enum EventTypeKindEnum: string
{
    case SOLO = 'solo';
    case GROUP = 'group';
}
