<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/**
 * Event - Information about a scheduled meeting
 * 
 * @package calendly\calendly\Models\Shared
 * @access public
 */
class Event
{
    /**
     * Information about the calendar event from the calendar provider.
     * 
     * @var \calendly\calendly\Models\Shared\LegacyCalendarEvent $calendarEvent
     */
	#[\JMS\Serializer\Annotation\SerializedName('calendar_event')]
    #[\JMS\Serializer\Annotation\Type('calendly\calendly\Models\Shared\LegacyCalendarEvent')]
    public LegacyCalendarEvent $calendarEvent;
    
    /**
     * Provides data pertaining to the cancellation of the Event
     * 
     * @var ?\calendly\calendly\Models\Shared\Cancellation $cancellation
     */
	#[\JMS\Serializer\Annotation\SerializedName('cancellation')]
    #[\JMS\Serializer\Annotation\Type('calendly\calendly\Models\Shared\Cancellation')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Cancellation $cancellation = null;
    
    /**
     * The moment when the event was created (e.g. "2020-01-02T03:04:05.678123Z")
     * 
     * @var \DateTime $createdAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $createdAt;
    
    /**
     * The moment the event was scheduled to end in UTC time (e.g. "2020-01-02T03:04:05.678123Z")
     * 
     * @var \DateTime $endTime
     */
	#[\JMS\Serializer\Annotation\SerializedName('end_time')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $endTime;
    
    /**
     * Additional people added to an event by an invitee
     * 
     * @var array<\calendly\calendly\Models\Shared\Guest> $eventGuests
     */
	#[\JMS\Serializer\Annotation\SerializedName('event_guests')]
    #[\JMS\Serializer\Annotation\Type('array<calendly\calendly\Models\Shared\Guest>')]
    public array $eventGuests;
    
    /**
     * Event membership list
     * 
     * @var array<\calendly\calendly\Models\Shared\EventEventMemberships> $eventMemberships
     */
	#[\JMS\Serializer\Annotation\SerializedName('event_memberships')]
    #[\JMS\Serializer\Annotation\Type('array<calendly\calendly\Models\Shared\EventEventMemberships>')]
    public array $eventMemberships;
    
    /**
     * The event type associated with this event
     * 
     * @var string $eventType
     */
	#[\JMS\Serializer\Annotation\SerializedName('event_type')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $eventType;
    
	#[\JMS\Serializer\Annotation\SerializedName('invitees_counter')]
    #[\JMS\Serializer\Annotation\Type('calendly\calendly\Models\Shared\EventInviteesCounter')]
    public EventInviteesCounter $inviteesCounter;
    
    /**
     * The polymorphic base type for an event location that Calendly supports
     * 
     * @var mixed $location
     */
	#[\JMS\Serializer\Annotation\SerializedName('location')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    public mixed $location;
    
    /**
     * The event name
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * The moment the event was scheduled to start in UTC time (e.g. "2020-01-02T03:04:05.678123Z").
     * 
     * @var \DateTime $startTime
     */
	#[\JMS\Serializer\Annotation\SerializedName('start_time')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $startTime;
    
    /**
     * Indicates if the event is "active" or "canceled"
     * 
     * @var \calendly\calendly\Models\Shared\EventStatusEnum $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<calendly\calendly\Models\Shared\EventStatusEnum>')]
    public EventStatusEnum $status;
    
    /**
     * The moment when the event was last updated (e.g. "2020-01-02T03:04:05.678123Z")
     * 
     * @var \DateTime $updatedAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('updated_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $updatedAt;
    
    /**
     * Canonical reference (unique identifier) for the resource
     * 
     * @var string $uri
     */
	#[\JMS\Serializer\Annotation\SerializedName('uri')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $uri;
    
	public function __construct()
	{
		$this->calendarEvent = new \calendly\calendly\Models\Shared\LegacyCalendarEvent();
		$this->cancellation = null;
		$this->createdAt = new \DateTime();
		$this->endTime = new \DateTime();
		$this->eventGuests = [];
		$this->eventMemberships = [];
		$this->eventType = "";
		$this->inviteesCounter = new \calendly\calendly\Models\Shared\EventInviteesCounter();
		$this->location = null;
		$this->name = "";
		$this->startTime = new \DateTime();
		$this->status = \calendly\calendly\Models\Shared\EventStatusEnum::ACTIVE;
		$this->updatedAt = new \DateTime();
		$this->uri = "";
	}
}
