<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** A formatted description of the kind of event type. */
enum EventTypeKindDescriptionEnum: string
{
    case COLLECTIVE = 'Collective';
    case GROUP = 'Group';
    case ONE_ON_ONE = 'One-on-One';
    case ROUND_ROBIN = 'Round Robin';
}
