<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/**
 * GoogleConference - Details about an Event that will take place using a Google Meet / Hangout conference
 * 
 * @package calendly\calendly\Models\Shared
 * @access public
 */
class GoogleConference
{
    /**
     * Google conference meeting url
     * 
     * @var string $joinUrl
     */
	#[\JMS\Serializer\Annotation\SerializedName('join_url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $joinUrl;
    
    /**
     * Indicates the current status of the Google conference
     * 
     * @var \calendly\calendly\Models\Shared\GoogleConferenceStatusEnum $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<calendly\calendly\Models\Shared\GoogleConferenceStatusEnum>')]
    public GoogleConferenceStatusEnum $status;
    
    /**
     * The event location is a Google Meet or Hangouts conference
     * 
     * @var \calendly\calendly\Models\Shared\GoogleConferenceTypeEnum $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<calendly\calendly\Models\Shared\GoogleConferenceTypeEnum>')]
    public GoogleConferenceTypeEnum $type;
    
	public function __construct()
	{
		$this->joinUrl = "";
		$this->status = \calendly\calendly\Models\Shared\GoogleConferenceStatusEnum::INITIATED;
		$this->type = \calendly\calendly\Models\Shared\GoogleConferenceTypeEnum::GOOGLE_CONFERENCE;
	}
}
