<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** The event location is a Google Meet or Hangouts conference */
enum GoogleConferenceTypeEnum: string
{
    case GOOGLE_CONFERENCE = 'google_conference';
}
