<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/**
 * GotoMeetingConference - Details about an Event that will take place using a GotoMeeting conference
 * 
 * @package calendly\calendly\Models\Shared
 * @access public
 */
class GotoMeetingConference
{
    /**
     * The conference metadata supplied by GoToMeeting
     * 
     * @var \calendly\calendly\Models\Shared\GotoMeetingConferenceData $data
     */
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('calendly\calendly\Models\Shared\GotoMeetingConferenceData')]
    public GotoMeetingConferenceData $data;
    
    /**
     * GoToMeeting conference meeting url
     * 
     * @var string $joinUrl
     */
	#[\JMS\Serializer\Annotation\SerializedName('join_url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $joinUrl;
    
    /**
     * Indicates the current status of the GoToMeeting conference
     * 
     * @var \calendly\calendly\Models\Shared\GotoMeetingConferenceStatusEnum $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<calendly\calendly\Models\Shared\GotoMeetingConferenceStatusEnum>')]
    public GotoMeetingConferenceStatusEnum $status;
    
    /**
     * The event location is a GoToMeeting conference
     * 
     * @var \calendly\calendly\Models\Shared\GotoMeetingConferenceTypeEnum $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<calendly\calendly\Models\Shared\GotoMeetingConferenceTypeEnum>')]
    public GotoMeetingConferenceTypeEnum $type;
    
	public function __construct()
	{
		$this->data = new \calendly\calendly\Models\Shared\GotoMeetingConferenceData();
		$this->joinUrl = "";
		$this->status = \calendly\calendly\Models\Shared\GotoMeetingConferenceStatusEnum::INITIATED;
		$this->type = \calendly\calendly\Models\Shared\GotoMeetingConferenceTypeEnum::GOTOMEETING;
	}
}
