<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** The event location is a GoToMeeting conference */
enum GotoMeetingConferenceTypeEnum: string
{
    case GOTOMEETING = 'gotomeeting';
}
