<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/**
 * InboundCall - Invitee will call meeting publisher at the specified phone number
 * 
 * @package calendly\calendly\Models\Shared
 * @access public
 */
class InboundCall
{
    /**
     * The phone number the invitee will use to call the event host (publisher)
     * 
     * @var string $location
     */
	#[\JMS\Serializer\Annotation\SerializedName('location')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $location;
    
    /**
     * 	
     * 
     * Indicates that the invitee will call the event host
     * 
     * @var \calendly\calendly\Models\Shared\InboundCallTypeEnum $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<calendly\calendly\Models\Shared\InboundCallTypeEnum>')]
    public InboundCallTypeEnum $type;
    
	public function __construct()
	{
		$this->location = "";
		$this->type = \calendly\calendly\Models\Shared\InboundCallTypeEnum::INBOUND_CALL;
	}
}
