<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/**
 * 	
 * 
 * Indicates that the invitee will call the event host
 */
enum InboundCallTypeEnum: string
{
    case INBOUND_CALL = 'inbound_call';
}
