<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/**
 * InPersonMeeting - Information about the physical (in-person) event location
 * 
 * @package calendly\calendly\Models\Shared
 * @access public
 */
class InPersonMeeting
{
    /**
     * The physical location specified by the event host (publisher)
     * 
     * @var string $location
     */
	#[\JMS\Serializer\Annotation\SerializedName('location')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $location;
    
    /**
     * Indicates that the event will be an in-person meeting.
     * 
     * @var \calendly\calendly\Models\Shared\InPersonMeetingTypeEnum $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<calendly\calendly\Models\Shared\InPersonMeetingTypeEnum>')]
    public InPersonMeetingTypeEnum $type;
    
	public function __construct()
	{
		$this->location = "";
		$this->type = \calendly\calendly\Models\Shared\InPersonMeetingTypeEnum::PHYSICAL;
	}
}
