<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** Indicates that the event will be an in-person meeting. */
enum InPersonMeetingTypeEnum: string
{
    case PHYSICAL = 'physical';
}
