<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** Indicates if the invitee is "active" or "canceled" */
enum InviteeStatusEnum: string
{
    case ACTIVE = 'active';
    case CANCELED = 'canceled';
}
