<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/**
 * InviteeSpecifiedLocation - Information about an event location that’s specified by the invitee.
 * 
 * @package calendly\calendly\Models\Shared
 * @access public
 */
class InviteeSpecifiedLocation
{
    /**
     * The event location description provided by the invitee
     * 
     * @var string $location
     */
	#[\JMS\Serializer\Annotation\SerializedName('location')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $location;
    
    /**
     * The event location selected by the invitee
     * 
     * @var \calendly\calendly\Models\Shared\InviteeSpecifiedLocationTypeEnum $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<calendly\calendly\Models\Shared\InviteeSpecifiedLocationTypeEnum>')]
    public InviteeSpecifiedLocationTypeEnum $type;
    
	public function __construct()
	{
		$this->location = "";
		$this->type = \calendly\calendly\Models\Shared\InviteeSpecifiedLocationTypeEnum::ASK_INVITEE;
	}
}
