<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** The event location selected by the invitee */
enum InviteeSpecifiedLocationTypeEnum: string
{
    case ASK_INVITEE = 'ask_invitee';
}
