<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/**
 * Invitee - An individual who has been invited to meet with a Calendly member
 * 
 * @package calendly\calendly\Models\Shared
 * @access public
 */
class Invitee
{
    /**
     * Link to cancelling the event for the invitee
     * 
     * @var string $cancelUrl
     */
	#[\JMS\Serializer\Annotation\SerializedName('cancel_url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $cancelUrl;
    
    /**
     * Provides data pertaining to the cancellation of the Event
     * 
     * @var ?\calendly\calendly\Models\Shared\Cancellation $cancellation
     */
	#[\JMS\Serializer\Annotation\SerializedName('cancellation')]
    #[\JMS\Serializer\Annotation\Type('calendly\calendly\Models\Shared\Cancellation')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Cancellation $cancellation = null;
    
    /**
     * The moment when the event was created (e.g. "2020-01-02T03:04:05.678123Z")
     * 
     * @var \DateTime $createdAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $createdAt;
    
    /**
     * The invitee’s email address
     * 
     * @var string $email
     */
	#[\JMS\Serializer\Annotation\SerializedName('email')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $email;
    
    /**
     * A reference to the event
     * 
     * @var string $event
     */
	#[\JMS\Serializer\Annotation\SerializedName('event')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $event;
    
    /**
     * The first name of the invitee who booked the event when the event type is configured to use separate fields for first name and last name. Null when event type is configured to use a single field for name.
     * 
     * @var string $firstName
     */
	#[\JMS\Serializer\Annotation\SerializedName('first_name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $firstName;
    
    /**
     * The last name of the invitee who booked the event when the event type is configured to use separate fields for first name and last name. Null when event type is configured to use a single field for name.
     * 
     * @var string $lastName
     */
	#[\JMS\Serializer\Annotation\SerializedName('last_name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $lastName;
    
    /**
     * The invitee’s name (in human-readable format)
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * Link to new invitee, after reschedule
     * 
     * @var string $newInvitee
     */
	#[\JMS\Serializer\Annotation\SerializedName('new_invitee')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $newInvitee;
    
    /**
     * Provides data pertaining to the associated no show for the Invitee
     * 
     * @var \calendly\calendly\Models\Shared\InviteeNoShow1 $noShow
     */
	#[\JMS\Serializer\Annotation\SerializedName('no_show')]
    #[\JMS\Serializer\Annotation\Type('calendly\calendly\Models\Shared\InviteeNoShow1')]
    public InviteeNoShow1 $noShow;
    
    /**
     * Reference to old Invitee instance that got rescheduled
     * 
     * @var string $oldInvitee
     */
	#[\JMS\Serializer\Annotation\SerializedName('old_invitee')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $oldInvitee;
    
    /**
     * Invitee payment
     * 
     * @var \calendly\calendly\Models\Shared\InviteePayment $payment
     */
	#[\JMS\Serializer\Annotation\SerializedName('payment')]
    #[\JMS\Serializer\Annotation\Type('calendly\calendly\Models\Shared\InviteePayment')]
    public InviteePayment $payment;
    
    /**
     * A collection of the invitee's responses to questions on the event booking confirmation form
     * 
     * @var array<\calendly\calendly\Models\Shared\InviteeQuestionAndAnswer> $questionsAndAnswers
     */
	#[\JMS\Serializer\Annotation\SerializedName('questions_and_answers')]
    #[\JMS\Serializer\Annotation\Type('array<calendly\calendly\Models\Shared\InviteeQuestionAndAnswer>')]
    public array $questionsAndAnswers;
    
    /**
     * Assuming reconfirmation is enabled for the event type, when reconfirmation is requested this object is present with a `created_at` that reflects when the reconfirmation notification was sent. Once the invitee has reconfirmed the `confirmed_at` attribute will change from `null` to a timestamp that reflects when they took action.
     * 
     * @var \calendly\calendly\Models\Shared\InviteeReconfirmation $reconfirmation
     */
	#[\JMS\Serializer\Annotation\SerializedName('reconfirmation')]
    #[\JMS\Serializer\Annotation\Type('calendly\calendly\Models\Shared\InviteeReconfirmation')]
    public InviteeReconfirmation $reconfirmation;
    
    /**
     * Link to rescheduling the event for the invitee
     * 
     * @var string $rescheduleUrl
     */
	#[\JMS\Serializer\Annotation\SerializedName('reschedule_url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $rescheduleUrl;
    
    /**
     * Indicates if this invitee has rescheduled. If `true`, a reference to the new Invitee instance is provided in the `new_invitee` field.
     * 
     * @var bool $rescheduled
     */
	#[\JMS\Serializer\Annotation\SerializedName('rescheduled')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $rescheduled;
    
    /**
     * Reference to a routing form submission that redirected the invitee to a booking page.
     * 
     * @var string $routingFormSubmission
     */
	#[\JMS\Serializer\Annotation\SerializedName('routing_form_submission')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $routingFormSubmission;
    
    /**
     * Indicates if the invitee is "active" or "canceled"
     * 
     * @var \calendly\calendly\Models\Shared\InviteeStatusEnum $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<calendly\calendly\Models\Shared\InviteeStatusEnum>')]
    public InviteeStatusEnum $status;
    
    /**
     * The phone number to use when sending text (SMS) reminders
     * 
     * @var string $textReminderNumber
     */
	#[\JMS\Serializer\Annotation\SerializedName('text_reminder_number')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $textReminderNumber;
    
    /**
     * Time zone to use when displaying time to the invitee
     * 
     * @var string $timezone
     */
	#[\JMS\Serializer\Annotation\SerializedName('timezone')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $timezone;
    
    /**
     * The UTM and Salesforce tracking parameters associated with an Invitee
     * 
     * @var \calendly\calendly\Models\Shared\InviteeTracking $tracking
     */
	#[\JMS\Serializer\Annotation\SerializedName('tracking')]
    #[\JMS\Serializer\Annotation\Type('calendly\calendly\Models\Shared\InviteeTracking')]
    public InviteeTracking $tracking;
    
    /**
     * The moment when the event was last updated (e.g. "2020-01-02T03:04:05.678123Z")
     * 
     * @var \DateTime $updatedAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('updated_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $updatedAt;
    
    /**
     * Canonical reference (unique identifier) for the invitee
     * 
     * @var string $uri
     */
	#[\JMS\Serializer\Annotation\SerializedName('uri')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $uri;
    
	public function __construct()
	{
		$this->cancelUrl = "";
		$this->cancellation = null;
		$this->createdAt = new \DateTime();
		$this->email = "";
		$this->event = "";
		$this->firstName = "";
		$this->lastName = "";
		$this->name = "";
		$this->newInvitee = "";
		$this->noShow = new \calendly\calendly\Models\Shared\InviteeNoShow1();
		$this->oldInvitee = "";
		$this->payment = new \calendly\calendly\Models\Shared\InviteePayment();
		$this->questionsAndAnswers = [];
		$this->reconfirmation = new \calendly\calendly\Models\Shared\InviteeReconfirmation();
		$this->rescheduleUrl = "";
		$this->rescheduled = false;
		$this->routingFormSubmission = "";
		$this->status = \calendly\calendly\Models\Shared\InviteeStatusEnum::ACTIVE;
		$this->textReminderNumber = "";
		$this->timezone = "";
		$this->tracking = new \calendly\calendly\Models\Shared\InviteeTracking();
		$this->updatedAt = new \DateTime();
		$this->uri = "";
	}
}
