<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** Payment provider */
enum InviteePaymentProviderEnum: string
{
    case STRIPE = 'stripe';
    case PAYPAL = 'paypal';
}
