<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** The currency format that the payment is in. */
enum InviteePaymentCurrencyEnum: string
{
    case AUD = 'AUD';
    case CAD = 'CAD';
    case EUR = 'EUR';
    case GBP = 'GBP';
    case USD = 'USD';
}
