<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/**
 * InviteeNoShow - Information about an invitees no show.
 * 
 * @package calendly\calendly\Models\Shared
 * @access public
 */
class InviteeNoShow
{
    /**
     * The moment when the no show was created
     * 
     * @var \DateTime $createdAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $createdAt;
    
    /**
     * Canonical reference (unique identifier) for the associated Invitee
     * 
     * @var string $invitee
     */
	#[\JMS\Serializer\Annotation\SerializedName('invitee')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $invitee;
    
    /**
     * Canonical reference (unique identifier) for the no show
     * 
     * @var string $uri
     */
	#[\JMS\Serializer\Annotation\SerializedName('uri')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $uri;
    
	public function __construct()
	{
		$this->createdAt = new \DateTime();
		$this->invitee = "";
		$this->uri = "";
	}
}
