<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/**
 * LegacyCalendarEvent - Information about the calendar event from the calendar provider.
 * 
 * @package calendly\calendly\Models\Shared
 * @access public
 */
class LegacyCalendarEvent
{
    /**
     * the id provided from the calendar provider for this calendar event.
     * 
     * @var string $externalId
     */
	#[\JMS\Serializer\Annotation\SerializedName('external_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $externalId;
    
    /**
     * Indicates the calendar provider the event belongs to.
     * 
     * @var \calendly\calendly\Models\Shared\LegacyCalendarEventKindEnum $kind
     */
	#[\JMS\Serializer\Annotation\SerializedName('kind')]
    #[\JMS\Serializer\Annotation\Type('enum<calendly\calendly\Models\Shared\LegacyCalendarEventKindEnum>')]
    public LegacyCalendarEventKindEnum $kind;
    
	public function __construct()
	{
		$this->externalId = "";
		$this->kind = \calendly\calendly\Models\Shared\LegacyCalendarEventKindEnum::EXCHANGE;
	}
}
