<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** Indicates the calendar provider the event belongs to. */
enum LegacyCalendarEventKindEnum: string
{
    case EXCHANGE = 'exchange';
    case GOOGLE = 'google';
    case ICLOUD = 'icloud';
    case OUTLOOK = 'outlook';
    case OUTLOOK_DESKTOP = 'outlook_desktop';
}
