<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/**
 * MicrosoftTeamsConference - Meeting will take place in a Microsoft Teams conference
 * 
 * @package calendly\calendly\Models\Shared
 * @access public
 */
class MicrosoftTeamsConference
{
    /**
     * The conference metadata supplied by Microsoft Teams
     * 
     * @var \calendly\calendly\Models\Shared\MicrosoftTeamsConferenceData $data
     */
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('calendly\calendly\Models\Shared\MicrosoftTeamsConferenceData')]
    public MicrosoftTeamsConferenceData $data;
    
    /**
     * Microsoft Teams meeting url
     * 
     * @var string $joinUrl
     */
	#[\JMS\Serializer\Annotation\SerializedName('join_url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $joinUrl;
    
    /**
     * Indicates the current status of the Microsoft Teams conference
     * 
     * @var \calendly\calendly\Models\Shared\MicrosoftTeamsConferenceStatusEnum $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<calendly\calendly\Models\Shared\MicrosoftTeamsConferenceStatusEnum>')]
    public MicrosoftTeamsConferenceStatusEnum $status;
    
    /**
     * The event location is a Zoom conference
     * 
     * @var \calendly\calendly\Models\Shared\MicrosoftTeamsConferenceTypeEnum $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<calendly\calendly\Models\Shared\MicrosoftTeamsConferenceTypeEnum>')]
    public MicrosoftTeamsConferenceTypeEnum $type;
    
	public function __construct()
	{
		$this->data = new \calendly\calendly\Models\Shared\MicrosoftTeamsConferenceData();
		$this->joinUrl = "";
		$this->status = \calendly\calendly\Models\Shared\MicrosoftTeamsConferenceStatusEnum::INITIATED;
		$this->type = \calendly\calendly\Models\Shared\MicrosoftTeamsConferenceTypeEnum::MICROSOFT_TEAMS_CONFERENCE;
	}
}
