<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/**
 * MicrosoftTeamsConferenceData - The conference metadata supplied by Microsoft Teams
 * 
 * @package calendly\calendly\Models\Shared
 * @access public
 */
class MicrosoftTeamsConferenceData
{
	#[\JMS\Serializer\Annotation\SerializedName('audioConferencing')]
    #[\JMS\Serializer\Annotation\Type('calendly\calendly\Models\Shared\MicrosoftTeamsConferenceDataAudioConferencing')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?MicrosoftTeamsConferenceDataAudioConferencing $audioConferencing = null;
    
    /**
     * The conference ID provided by Microsoft Teams
     * 
     * @var ?string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $id = null;
    
	public function __construct()
	{
		$this->audioConferencing = null;
		$this->id = null;
	}
}
