<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** The event location is a Zoom conference */
enum MicrosoftTeamsConferenceTypeEnum: string
{
    case MICROSOFT_TEAMS_CONFERENCE = 'microsoft_teams_conference';
}
