<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** The user's role in the organization */
enum OrganizationMembershipRoleEnum: string
{
    case USER = 'user';
    case ADMIN = 'admin';
    case OWNER = 'owner';
}
