<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


class OrganizationMembership
{
    /**
     * The moment when the membership record was created (e.g. "2020-01-02T03:04:05.678123Z")
     * 
     * @var \DateTime $createdAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $createdAt;
    
    /**
     * A unique reference to the organization
     * 
     * @var string $organization
     */
	#[\JMS\Serializer\Annotation\SerializedName('organization')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $organization;
    
    /**
     * The user's role in the organization
     * 
     * @var \calendly\calendly\Models\Shared\OrganizationMembershipRoleEnum $role
     */
	#[\JMS\Serializer\Annotation\SerializedName('role')]
    #[\JMS\Serializer\Annotation\Type('enum<calendly\calendly\Models\Shared\OrganizationMembershipRoleEnum>')]
    public OrganizationMembershipRoleEnum $role;
    
    /**
     * The moment when the membership record was last updated (e.g. "2020-01-02T03:04:05.678123Z")
     * 
     * @var \DateTime $updatedAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('updated_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $updatedAt;
    
    /**
     * Canonical reference (unique identifier) for the membership
     * 
     * @var string $uri
     */
	#[\JMS\Serializer\Annotation\SerializedName('uri')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $uri;
    
    /**
     * Information about the user.
     * 
     * @var \calendly\calendly\Models\Shared\OrganizationMembershipUser $user
     */
	#[\JMS\Serializer\Annotation\SerializedName('user')]
    #[\JMS\Serializer\Annotation\Type('calendly\calendly\Models\Shared\OrganizationMembershipUser')]
    public OrganizationMembershipUser $user;
    
	public function __construct()
	{
		$this->createdAt = new \DateTime();
		$this->organization = "";
		$this->role = \calendly\calendly\Models\Shared\OrganizationMembershipRoleEnum::USER;
		$this->updatedAt = new \DateTime();
		$this->uri = "";
		$this->user = new \calendly\calendly\Models\Shared\OrganizationMembershipUser();
	}
}
