<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/**
 * OrganizationInvitation - Organization Invitation object
 * 
 * @package calendly\calendly\Models\Shared
 * @access public
 */
class OrganizationInvitation
{
    /**
     * The moment the invitation was created (e.g. “2020-01-02T03:04:05.678123Z")
     * 
     * @var \DateTime $createdAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $createdAt;
    
    /**
     * The email address of the person who was invited to join the organization
     * 
     * @var string $email
     */
	#[\JMS\Serializer\Annotation\SerializedName('email')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $email;
    
    /**
     * The moment the invitation was last sent (e.g. "2020-01-02T03:04:05.678123Z")
     * 
     * @var \DateTime $lastSentAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('last_sent_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $lastSentAt;
    
    /**
     * Canonical reference (unique identifier) for the organization
     * 
     * @var string $organization
     */
	#[\JMS\Serializer\Annotation\SerializedName('organization')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $organization;
    
    /**
     * The status of the invitation ("pending", "accepted", or "declined")
     * 
     * @var \calendly\calendly\Models\Shared\OrganizationInvitationStatusEnum $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<calendly\calendly\Models\Shared\OrganizationInvitationStatusEnum>')]
    public OrganizationInvitationStatusEnum $status;
    
    /**
     * The moment the invitation was last updated (e.g. "2020-01-02T03:04:05.678123Z")
     * 
     * @var \DateTime $updatedAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('updated_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $updatedAt;
    
    /**
     * Canonical reference (unique identifier) for the organization invitation
     * 
     * @var string $uri
     */
	#[\JMS\Serializer\Annotation\SerializedName('uri')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $uri;
    
    /**
     * When the invitation is accepted, a reference to the user who accepted the invitation
     * 
     * @var ?string $user
     */
	#[\JMS\Serializer\Annotation\SerializedName('user')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $user = null;
    
	public function __construct()
	{
		$this->createdAt = new \DateTime();
		$this->email = "";
		$this->lastSentAt = new \DateTime();
		$this->organization = "";
		$this->status = \calendly\calendly\Models\Shared\OrganizationInvitationStatusEnum::PENDING;
		$this->updatedAt = new \DateTime();
		$this->uri = "";
		$this->user = null;
	}
}
