<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** Indicates that the event host (publisher) will call the invitee */
enum OutboundCallTypeEnum: string
{
    case OUTBOUND_CALL = 'outbound_call';
}
