<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/**
 * OutboundCall - Meeting publisher will call the Invitee
 * 
 * @package calendly\calendly\Models\Shared
 * @access public
 */
class OutboundCall
{
    /**
     * The phone number the event host (publisher) will use to call the invitee
     * 
     * @var string $location
     */
	#[\JMS\Serializer\Annotation\SerializedName('location')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $location;
    
    /**
     * Indicates that the event host (publisher) will call the invitee
     * 
     * @var \calendly\calendly\Models\Shared\OutboundCallTypeEnum $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<calendly\calendly\Models\Shared\OutboundCallTypeEnum>')]
    public OutboundCallTypeEnum $type;
    
	public function __construct()
	{
		$this->location = "";
		$this->type = \calendly\calendly\Models\Shared\OutboundCallTypeEnum::OUTBOUND_CALL;
	}
}
