<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


class Pagination
{
    /**
     * The number of rows to return
     * 
     * @var float $count
     */
	#[\JMS\Serializer\Annotation\SerializedName('count')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $count;
    
    /**
     * URI to return the next page of an ordered list ("null" indicates no additional results are available)
     * 
     * @var string $nextPage
     */
	#[\JMS\Serializer\Annotation\SerializedName('next_page')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $nextPage;
    
    /**
     * Token to return the next page of an ordered list ("null" indicates no additional results are available)
     * 
     * @var string $nextPageToken
     */
	#[\JMS\Serializer\Annotation\SerializedName('next_page_token')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $nextPageToken;
    
    /**
     * URI to return the previous page of an ordered list ("null" indicates no additional results are available)
     * 
     * @var string $previousPage
     */
	#[\JMS\Serializer\Annotation\SerializedName('previous_page')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $previousPage;
    
    /**
     * Token to return the previous page of an ordered list ("null" indicates no additional results are available)
     * 
     * @var string $previousPageToken
     */
	#[\JMS\Serializer\Annotation\SerializedName('previous_page_token')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $previousPageToken;
    
	public function __construct()
	{
		$this->count = 0;
		$this->nextPage = "";
		$this->nextPageToken = "";
		$this->previousPage = "";
		$this->previousPageToken = "";
	}
}
