<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/**
 * Profile - The publicly visible profile of a User or a Team that's associated with the Event Type (note: some Event Types don't have profiles)
 * 
 * @package calendly\calendly\Models\Shared
 * @access public
 */
class Profile
{
    /**
     * Human-readable name for the profile of the user that's associated with the event type
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * The unique reference to the user associated with the profile
     * 
     * @var string $owner
     */
	#[\JMS\Serializer\Annotation\SerializedName('owner')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $owner;
    
    /**
     * Indicates if the profile belongs to a "user" (individual) or "team"
     * 
     * @var \calendly\calendly\Models\Shared\ProfileTypeEnum $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<calendly\calendly\Models\Shared\ProfileTypeEnum>')]
    public ProfileTypeEnum $type;
    
	public function __construct()
	{
		$this->name = "";
		$this->owner = "";
		$this->type = \calendly\calendly\Models\Shared\ProfileTypeEnum::USER;
	}
}
