<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** Indicates if the profile belongs to a "user" (individual) or "team" */
enum ProfileTypeEnum: string
{
    case USER = 'User';
    case TEAM = 'Team';
}
