<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** Question type: name, text input, email, phone, textarea input, dropdown list or radio button list. */
enum QuestionTypeEnum: string
{
    case NAME = 'name';
    case TEXT = 'text';
    case EMAIL = 'email';
    case PHONE = 'phone';
    case TEXTAREA = 'textarea';
    case SELECT = 'select';
    case RADIOS = 'radios';
}
