<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/**
 * Question - Routing form questions.
 * 
 * @package calendly\calendly\Models\Shared
 * @access public
 */
class Question
{
    /**
     * The respondent’s option(s) for "select" or "radios" types of questions.
     * 
     * @var array<string> $answerChoices
     */
	#[\JMS\Serializer\Annotation\SerializedName('answer_choices')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    public array $answerChoices;
    
    /**
     * Question name (in human-readable format).
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * true if an answer to the question is required for respondents to submit the routing form; false if not required.
     * 
     * 
     * 
     * @var bool $required
     */
	#[\JMS\Serializer\Annotation\SerializedName('required')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $required;
    
    /**
     * Question type: name, text input, email, phone, textarea input, dropdown list or radio button list.
     * 
     * @var \calendly\calendly\Models\Shared\QuestionTypeEnum $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<calendly\calendly\Models\Shared\QuestionTypeEnum>')]
    public QuestionTypeEnum $type;
    
    /**
     * Unique identifier for the routing form question.
     * 
     * @var string $uuid
     */
	#[\JMS\Serializer\Annotation\SerializedName('uuid')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $uuid;
    
	public function __construct()
	{
		$this->answerChoices = [];
		$this->name = "";
		$this->required = false;
		$this->type = \calendly\calendly\Models\Shared\QuestionTypeEnum::NAME;
		$this->uuid = "";
	}
}
