<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** Type of the respondent resource that submitted the form and scheduled a meeting. */
enum RoutingFormSubmissionSubmitterTypeEnum: string
{
    case INVITEE = 'Invitee';
    case NULL = 'null';
}
