<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/**
 * RoutingFormSubmission - Information about a Routing Form Submission.
 * 
 * @package calendly\calendly\Models\Shared
 * @access public
 */
class RoutingFormSubmission
{
    /**
     * The moment the routing form was submitted.
     * 
     * @var \DateTime $createdAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $createdAt;
    
    /**
     * All Routing Form Submission questions with answers.
     * 
     * @var array<\calendly\calendly\Models\Shared\SubmissionQuestionAndAnswer> $questionsAndAnswers
     */
	#[\JMS\Serializer\Annotation\SerializedName('questions_and_answers')]
    #[\JMS\Serializer\Annotation\Type('array<calendly\calendly\Models\Shared\SubmissionQuestionAndAnswer>')]
    public array $questionsAndAnswers;
    
    /**
     * The polymorphic base type for a Routing Form Submission result.
     * 
     * @var mixed $result
     */
	#[\JMS\Serializer\Annotation\SerializedName('result')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public mixed $result = null;
    
    /**
     * The URI of the routing form that's associated with the submission.
     * 
     * @var string $routingForm
     */
	#[\JMS\Serializer\Annotation\SerializedName('routing_form')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $routingForm;
    
    /**
     * The reference to the Invitee resource when routing form submission results in a scheduled meeting.
     * 
     * @var string $submitter
     */
	#[\JMS\Serializer\Annotation\SerializedName('submitter')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $submitter;
    
    /**
     * Type of the respondent resource that submitted the form and scheduled a meeting.
     * 
     * @var \calendly\calendly\Models\Shared\RoutingFormSubmissionSubmitterTypeEnum $submitterType
     */
	#[\JMS\Serializer\Annotation\SerializedName('submitter_type')]
    #[\JMS\Serializer\Annotation\Type('enum<calendly\calendly\Models\Shared\RoutingFormSubmissionSubmitterTypeEnum>')]
    public RoutingFormSubmissionSubmitterTypeEnum $submitterType;
    
    /**
     * The UTM and Salesforce tracking parameters associated with a Routing Form Submission.
     * 
     * @var \calendly\calendly\Models\Shared\SubmissionTracking $tracking
     */
	#[\JMS\Serializer\Annotation\SerializedName('tracking')]
    #[\JMS\Serializer\Annotation\Type('calendly\calendly\Models\Shared\SubmissionTracking')]
    public SubmissionTracking $tracking;
    
    /**
     * The moment when the routing form submission was last updated.
     * 
     * @var \DateTime $updatedAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('updated_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $updatedAt;
    
    /**
     * Canonical reference (unique identifier) for the routing form submission.
     * 
     * @var string $uri
     */
	#[\JMS\Serializer\Annotation\SerializedName('uri')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $uri;
    
	public function __construct()
	{
		$this->createdAt = new \DateTime();
		$this->questionsAndAnswers = [];
		$this->result = null;
		$this->routingForm = "";
		$this->submitter = "";
		$this->submitterType = \calendly\calendly\Models\Shared\RoutingFormSubmissionSubmitterTypeEnum::INVITEE;
		$this->tracking = new \calendly\calendly\Models\Shared\SubmissionTracking();
		$this->updatedAt = new \DateTime();
		$this->uri = "";
	}
}
