<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** Indicates if the form is in "draft" or "published" status. */
enum RoutingFormStatusEnum: string
{
    case DRAFT = 'draft';
    case PUBLISHED = 'published';
}
