<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/**
 * RoutingForm - Information about a routing form.
 * 
 * @package calendly\calendly\Models\Shared
 * @access public
 */
class RoutingForm
{
    /**
     * The moment the routing form was created.
     * 
     * @var \DateTime $createdAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $createdAt;
    
    /**
     * The routing form name (in human-readable format).
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * The URI of the organization that's associated with the routing form.
     * 
     * @var string $organization
     */
	#[\JMS\Serializer\Annotation\SerializedName('organization')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $organization;
    
    /**
     * An ordered collection of Routing Form non-deleted questions.
     * 
     * @var array<\calendly\calendly\Models\Shared\Question> $questions
     */
	#[\JMS\Serializer\Annotation\SerializedName('questions')]
    #[\JMS\Serializer\Annotation\Type('array<calendly\calendly\Models\Shared\Question>')]
    public array $questions;
    
    /**
     * Indicates if the form is in "draft" or "published" status.
     * 
     * @var \calendly\calendly\Models\Shared\RoutingFormStatusEnum $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<calendly\calendly\Models\Shared\RoutingFormStatusEnum>')]
    public RoutingFormStatusEnum $status;
    
    /**
     * The moment when the routing form was last updated.
     * 
     * @var \DateTime $updatedAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('updated_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $updatedAt;
    
    /**
     * Canonical reference (unique identifier) for the routing form.
     * 
     * 
     * 
     * @var string $uri
     */
	#[\JMS\Serializer\Annotation\SerializedName('uri')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $uri;
    
	public function __construct()
	{
		$this->createdAt = new \DateTime();
		$this->name = "";
		$this->organization = "";
		$this->questions = [];
		$this->status = \calendly\calendly\Models\Shared\RoutingFormStatusEnum::DRAFT;
		$this->updatedAt = new \DateTime();
		$this->uri = "";
	}
}
