<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** Resource type (currently, this is always EventType) */
enum ShareSchedulingLinksOwnerTypeEnum: string
{
    case EVENT_TYPE = 'EventType';
}
