<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** Indicates that the routing form submission resulted in a redirect to an event type booking page. */
enum SubmissionEventTypeResultTypeEnum: string
{
    case EVENT_TYPE = 'event_type';
}
