<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/**
 * SubmissionQuestionAndAnswer - All Routing Form Submission questions with answers.
 * 
 * @package calendly\calendly\Models\Shared
 * @access public
 */
class SubmissionQuestionAndAnswer
{
    /**
     * Answer provided by the respondent when the form was submitted.
     * 
     * @var ?string $answer
     */
	#[\JMS\Serializer\Annotation\SerializedName('answer')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $answer = null;
    
    /**
     * Question name (in human-readable format).
     * 
     * @var string $question
     */
	#[\JMS\Serializer\Annotation\SerializedName('question')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $question;
    
    /**
     * Unique identifier for the routing form question.
     * 
     * @var string $questionUuid
     */
	#[\JMS\Serializer\Annotation\SerializedName('question_uuid')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $questionUuid;
    
	public function __construct()
	{
		$this->answer = null;
		$this->question = "";
		$this->questionUuid = "";
	}
}
