<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/**
 * SubmissionCustomMessageResultValue - Contains an object with custom message headline and body.
 * 
 * @package calendly\calendly\Models\Shared
 * @access public
 */
class SubmissionCustomMessageResultValue
{
    /**
     * Body text displayed when answers don't match any routes.
     * 
     * @var string $body
     */
	#[\JMS\Serializer\Annotation\SerializedName('body')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $body;
    
    /**
     * Headline displayed when answers don't match any routes.
     * 
     * @var string $headline
     */
	#[\JMS\Serializer\Annotation\SerializedName('headline')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $headline;
    
	public function __construct()
	{
		$this->body = "";
		$this->headline = "";
	}
}
