<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/**
 * SubmissionCustomMessageResult - Information about the custom message Routing Form Submission result.
 * 
 * @package calendly\calendly\Models\Shared
 * @access public
 */
class SubmissionCustomMessageResult
{
    /**
     * Indicates if the routing form submission resulted in a custom "thank you" message.
     * 
     * @var \calendly\calendly\Models\Shared\SubmissionCustomMessageResultTypeEnum $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<calendly\calendly\Models\Shared\SubmissionCustomMessageResultTypeEnum>')]
    public SubmissionCustomMessageResultTypeEnum $type;
    
    /**
     * Contains an object with custom message headline and body.
     * 
     * @var \calendly\calendly\Models\Shared\SubmissionCustomMessageResultValue $value
     */
	#[\JMS\Serializer\Annotation\SerializedName('value')]
    #[\JMS\Serializer\Annotation\Type('calendly\calendly\Models\Shared\SubmissionCustomMessageResultValue')]
    public SubmissionCustomMessageResultValue $value;
    
	public function __construct()
	{
		$this->type = \calendly\calendly\Models\Shared\SubmissionCustomMessageResultTypeEnum::CUSTOM_MESSAGE;
		$this->value = new \calendly\calendly\Models\Shared\SubmissionCustomMessageResultValue();
	}
}
