<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/**
 * SubmissionExternalUrlResult - Information about the external URL Routing Form Submission result.
 * 
 * @package calendly\calendly\Models\Shared
 * @access public
 */
class SubmissionExternalUrlResult
{
    /**
     * Indicates that the routing form submission resulted in a redirect to an external URL.
     * 
     * @var \calendly\calendly\Models\Shared\SubmissionExternalUrlResultTypeEnum $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<calendly\calendly\Models\Shared\SubmissionExternalUrlResultTypeEnum>')]
    public SubmissionExternalUrlResultTypeEnum $type;
    
    /**
     * The external URL the respondent were redirected to.
     * 
     * @var string $value
     */
	#[\JMS\Serializer\Annotation\SerializedName('value')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $value;
    
	public function __construct()
	{
		$this->type = \calendly\calendly\Models\Shared\SubmissionExternalUrlResultTypeEnum::EXTERNAL_URL;
		$this->value = "";
	}
}
