<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** Indicates if the routing form submission resulted in a custom "thank you" message. */
enum SubmissionCustomMessageResultTypeEnum: string
{
    case CUSTOM_MESSAGE = 'custom_message';
}
