<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** Indicates whether the scheduled event is internal or external */
enum UserBusyTimeTypeEnum: string
{
    case CALENDLY = 'calendly';
    case EXTERNAL = 'external';
}
