<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** The event location is a WebEx conference */
enum WebExConferenceTypeEnum: string
{
    case WEBEX_CONFERENCE = 'webex_conference';
}
