<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** The scope of the webhook subscription */
enum WebhookSubscriptionScopeEnum: string
{
    case USER = 'user';
    case ORGANIZATION = 'organization';
}
