<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


/** Indicates if the webhook subscription is "active" or "disabled" */
enum WebhookSubscriptionStateEnum: string
{
    case ACTIVE = 'active';
    case DISABLED = 'disabled';
}
