<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


class ZoomConferenceDataSettings
{
    /**
     * $globalDialInNumbers
     * 
     * @var ?array<\calendly\calendly\Models\Shared\ZoomConferenceDataSettingsGlobalDialInNumbers> $globalDialInNumbers
     */
	#[\JMS\Serializer\Annotation\SerializedName('global_dial_in_numbers')]
    #[\JMS\Serializer\Annotation\Type('array<calendly\calendly\Models\Shared\ZoomConferenceDataSettingsGlobalDialInNumbers>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $globalDialInNumbers = null;
    
	public function __construct()
	{
		$this->globalDialInNumbers = null;
	}
}
