<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace calendly\calendly\Models\Shared;


class ZoomConferenceDataExtra
{
    /**
     * Zoom International Dial-in Numbers URL
     * 
     * @var ?string $intlNumbersUrl
     */
	#[\JMS\Serializer\Annotation\SerializedName('intl_numbers_url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $intlNumbersUrl = null;
    
	public function __construct()
	{
		$this->intlNumbersUrl = null;
	}
}
